import { digests } from '#/.velite';
import Link from 'next/link';
import { ScrambleText } from '@/components/ui/ScrambleText';

export const metadata = {
  title: 'AI 每日情报 - Horizon Digest',
  description: '由 Horizon 驱动的每日 AI/ML 技术情报，自动聚合、AI 评分精选',
};

export default function DigestPage() {
  const published = digests
    .filter((d) => d.published)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  return (
    <div className="container mx-auto px-4 py-12 md:py-16 max-w-6xl">
      <div className="mb-12">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wide mb-4">
          ⚡ Daily · Auto-generated by Horizon
        </div>
        <h1 className="font-display text-5xl md:text-6xl font-black mb-4 text-text-primary">
          <ScrambleText trigger={false} duration={700}>
            AI 每日情报
          </ScrambleText>
        </h1>
        <p className="text-text-secondary text-xl max-w-2xl">
          每天从数十个 AI/ML 信息源中自动聚合、评分筛选的技术情报简报。
          由{' '}
          <a
            href="https://github.com/wdf0512/Horizon"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            Horizon
          </a>{' '}
          驱动，北京时间每日 09:00 自动更新。
        </p>
      </div>

      {published.length === 0 ? (
        <div className="text-center py-20">
          <div className="text-6xl mb-4">📡</div>
          <h3 className="font-display text-2xl font-bold mb-2 text-text-primary">
            暂无情报
          </h3>
          <p className="text-text-secondary">
            第一份情报将于明天 09:00 自动生成
          </p>
        </div>
      ) : (
        <div className="grid gap-3">
          {published.map((digest) => {
            const d = new Date(digest.date);
            return (
              <Link
                key={digest.slug}
                href={`/digest/${digest.slug}`}
                className="group flex items-center justify-between p-5 rounded-2xl border border-border hover:border-primary/40 bg-background hover:bg-surface transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg"
              >
                <div className="flex items-center gap-5">
                  <div className="text-center w-12 flex-shrink-0">
                    <div className="text-2xl font-black font-display text-primary leading-none">
                      {d.getDate()}
                    </div>
                    <div className="text-xs text-text-secondary uppercase tracking-wide mt-0.5">
                      {d.toLocaleDateString('zh-CN', { month: 'short' })}
                    </div>
                  </div>
                  <div>
                    <h2 className="font-display text-lg font-bold text-text-primary group-hover:text-primary transition-colors leading-snug">
                      {digest.title}
                    </h2>
                    {digest.description && (
                      <p className="text-text-secondary text-sm mt-0.5">
                        {digest.description}
                      </p>
                    )}
                  </div>
                </div>
                <div className="flex items-center gap-3 flex-shrink-0 ml-4">
                  {digest.item_count > 0 && (
                    <span className="hidden sm:inline-flex px-2.5 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold">
                      {digest.item_count} 条精选
                    </span>
                  )}
                  <span className="text-text-muted group-hover:text-primary transition-colors text-lg">
                    →
                  </span>
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
