import { digests } from '#/.velite';
import Link from 'next/link';
import { ScrambleText } from '@/components/ui/ScrambleText';

export const metadata = {
  title: 'AI 每日情报 - Horizon Digest',
  description: '由 Horizon 驱动的每日 AI/ML 技术情报，自动聚合、AI 评分精选',
};

export default function DigestPage() {
  const published = digests
    .filter((d) => d.published && d.item_count > 0)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  return (
    <div className="container mx-auto px-4 py-12 md:py-16 max-w-6xl">
      {/* Header */}
      <div className="mb-12">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-semibold uppercase tracking-wide mb-4">
          ⚡ Daily · Auto-generated by Horizon
        </div>
        <h1 className="font-display text-5xl md:text-6xl font-black mb-4 text-text-primary">
          <ScrambleText trigger={false} duration={700}>
            AI 每日情报
          </ScrambleText>
        </h1>
        <p className="text-text-secondary text-xl max-w-2xl">
          每天从数十个 AI/ML 信息源中自动聚合、评分筛选的技术情报简报。由{' '}
          <a
            href="https://github.com/wdf0512/Horizon"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            Horizon
          </a>{' '}
          驱动，北京时间每日 09:00 自动更新。
        </p>
      </div>

      {published.length === 0 ? (
        <div className="text-center py-20">
          <div className="text-6xl mb-4">📡</div>
          <h3 className="font-display text-2xl font-bold mb-2 text-text-primary">暂无情报</h3>
          <p className="text-text-secondary">第一份情报将于明天 09:00 自动生成</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {published.map((digest) => {
            const d = new Date(digest.date);
            const dateLabel = d.toLocaleDateString('zh-CN', { month: 'long', day: 'numeric' });
            const weekday = d.toLocaleDateString('zh-CN', { weekday: 'short' });
            return (
              <Link
                key={digest.slug}
                href={`/digest/${digest.slug}`}
                className="group block rounded-2xl border border-border hover:border-primary/40 bg-background hover:shadow-xl transition-all duration-300 overflow-hidden hover:-translate-y-1"
              >
                {/* Cover image */}
                <div className="relative aspect-video overflow-hidden bg-surface">
                  {digest.cover_image ? (
                    <img
                      src={digest.cover_image}
                      alt={digest.title}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                  ) : (
                    <div className="w-full h-full bg-gradient-to-br from-primary/20 via-primary/5 to-background flex items-center justify-center">
                      <span className="text-7xl opacity-10 select-none">⚡</span>
                    </div>
                  )}
                  <div className="absolute inset-0 bg-gradient-to-t from-background/80 via-transparent to-transparent" />

                  {/* Date badge */}
                  <div className="absolute top-3 left-3">
                    <span className="px-2.5 py-1 rounded-lg bg-background/80 backdrop-blur-sm text-xs font-semibold text-text-secondary border border-border/50">
                      {dateLabel} {weekday}
                    </span>
                  </div>

                  {/* Item count badge */}
                  {digest.item_count > 0 && (
                    <div className="absolute top-3 right-3">
                      <span className="px-2.5 py-1 rounded-lg bg-primary text-xs font-bold text-white shadow-lg">
                        {digest.item_count} 条精选
                      </span>
                    </div>
                  )}
                </div>

                {/* Card body */}
                <div className="p-5">
                  <h2 className="font-display text-lg font-bold text-text-primary group-hover:text-primary transition-colors leading-snug mb-2 line-clamp-2">
                    {digest.title}
                  </h2>
                  {digest.description && (
                    <p className="text-text-secondary text-sm leading-relaxed line-clamp-2">
                      {digest.description}
                    </p>
                  )}
                  <div className="mt-4 flex items-center justify-between text-xs text-text-muted">
                    {digest.total_fetched > 0 && (
                      <span>📥 从 {digest.total_fetched} 条内容筛选</span>
                    )}
                    <span className="text-primary font-semibold group-hover:translate-x-1 transition-transform inline-block ml-auto">
                      阅读全文 →
                    </span>
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
